import { Inter } from 'next/font/google';
import './globals.css';
import { ReduxProvider } from '@lib/redux/provider';
import store from '@lib/redux/store';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'AI S',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
